### ISSUE TITLE
Can't start GDB under virtualenv on windows

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/valinor#12]
The multiprocessing module fails to find the main module when forking for the gdb server process.

The difference between virtualenv/not seems to be:

under virtual env
```
main_path: C:\yotta\workspace\Scripts\valinor.exe\__main__.py
main_name: __main__
```

not under a virtual env:
```
main_path: C:\yotta\python\Scripts\valinor-script.py
main_name: valinor-script
```

The error message in a virtual env is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\yotta\python\Lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\yotta\python\Lib\multiprocessing\forking.py", line 492, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "C:\yotta\python\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\yotta\python\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\yotta\workspace\Scripts\valinor.exe\__main__.py", line 9, in <module>
  File "c:\yotta\workspace\lib\site-packages\valinor\main.py", line 140, in main
    launch_fn(projectfiles['files'], executable)
  File "c:\yotta\workspace\lib\site-packages\valinor\gdb.py", line 90, in launch_arm_gdb
    raise Exception('gdb server failed to start')
Exception: gdb server failed to start
```

I can't find a lot of other reports of this error, which suggests either valinor is doing something wrong, or the virtualenv setup is broken somehow.

cc @sg-

**Comment by autopulated** [comment]
(this isn't an issue on non-windows platforms because multiprocessing uses a completely different implementation, which doesn't rely on running `python -c "from multiprocessing.forking import main; main()"`, but instead does a real fork)
