### ISSUE TITLE
Connection timed out when using valinor on ubuntu

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/valinor#21]
`sudo pyocd-gdbserver` works fine. Problem likely in valinor.

```
liyzho01@e105699-lin:/work/iot/ble-examples/BLE_LED$ sudo yt debug ble-led
info: found ble-led at source/ble-led
info: preparing PyOCD gdbserver...
info: finding connected board...
is_kernel_driver_active
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/interface/pyusb_backend.py", line 64, in rx_task
    self.rcv_data.append(self.ep_in.read(self.ep_in.wMaxPacketSize, -1))
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 364, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 918, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 507, in intr_read
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 562, in __read
    timeout
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
USBError: [Errno None] Connection timed out
```

**Comment by 0xc0170** [comment]
Add info: using latest pyOCD master (as of today), valinor - 0.0.12, OS - ubuntu

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1423

**Comment by autopulated** [comment]
yotta drops root privileges before running the debug command.

You should have the permissions you need to debug things without sudo-ing though, I think?

**Comment by bogdanm** [comment]
You should, yes. That doesn't look like a permission error though.

**Comment by LiyouZhou** [comment]
I always needed sudo on my system. Maybe its just my setup?

**Comment by autopulated** [comment]
@LiyouZhou You probably want to create a [udev rule](http://stackoverflow.com/a/8582398/233201) to give yourself non-root access to USB devices.

I'm going to close this issue as "won't fix", as I don't think yotta should allow debug commands to run with root privileges, it should be searchable for anyone else with the same problem
